0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/sandeep/Documents/IITM/Deep Learning/main.py", line 120, in <module>
    model.sgd(train_X,train_y)
  File "/home/sandeep/Documents/IITM/Deep Learning/FFNN.py", line 221, in sgd
    acc ,loss = self.evaluate_model_performance(train_X,train_Y)
  File "/home/sandeep/Documents/IITM/Deep Learning/FFNN.py", line 449, in evaluate_model_performance
    cumullative_loss.append(self.compute_loss(y,pred))
  File "/home/sandeep/Documents/IITM/Deep Learning/FFNN.py", line 100, in compute_loss
    p_k = y_pred[max_index]
IndexError: invalid index to scalar variable.
Traceback (most recent call last):
  File "/home/sandeep/Documents/IITM/Deep Learning/main.py", line 120, in <module>
    model.sgd(train_X,train_y)
  File "/home/sandeep/Documents/IITM/Deep Learning/FFNN.py", line 221, in sgd
    acc ,loss = self.evaluate_model_performance(train_X,train_Y)
  File "/home/sandeep/Documents/IITM/Deep Learning/FFNN.py", line 449, in evaluate_model_performance
    cumullative_loss.append(self.compute_loss(y,pred))
  File "/home/sandeep/Documents/IITM/Deep Learning/FFNN.py", line 100, in compute_loss
    p_k = y_pred[max_index]
IndexError: invalid index to scalar variable.